# Generated by Django 3.2.7 on 2021-09-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRJob',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('job_status', models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('CP', 'Complete'), ('FD', 'Failed')], default='NS', max_length=2)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('files_processed', models.IntegerField(default=0)),
                ('total_files', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TargetFile',
            fields=[
                ('identifier', models.UUIDField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('file_name', models.TextField()),
                ('size_bytes', models.IntegerField(null=True)),
                ('file_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OCRTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tesseract_version', models.CharField(max_length=32)),
                ('leptonica_version', models.CharField(max_length=32)),
                ('image_type', models.CharField(max_length=32)),
                ('transcript', models.TextField()),
                ('size_bytes', models.IntegerField()),
                ('page_num', models.IntegerField()),
                ('total_pages', models.IntegerField()),
                ('related_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ocrjob')),
            ],
        ),
        migrations.AddField(
            model_name='ocrjob',
            name='target_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.targetfile'),
        ),
    ]
