# Generated by Django 3.2.7 on 2021-09-22 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetfile',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='targetfile',
            name='file_type',
        ),
        migrations.AddField(
            model_name='targetfile',
            name='file_uri',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='targetfile',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='targetfile',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='targetfile',
            name='size_bytes',
            field=models.IntegerField(default=0),
        ),
    ]
